language: python
python:
  - "2.7"

services:
  - redis-server

before_install:
  - sudo apt-get update -qq

install:
  - pip install . --use-mirrors
  - pip install coveralls

script: coverage run --source=redisORM nosetests

after_success:
  coveralls
